export const colorVariants = {
  outline: {
    primary: "border-primary text-primary hover:bg-primary hover:text-white",
    secondary: "border-secondary text-secondary hover:bg-secondary hover:text-white",
    info: "border-info text-info hover:bg-info hover:text-white",
    neutral: "border-neutral text-neutral hover:bg-neutral hover:text-white",
    error: "border-error text-error hover:bg-error hover:text-white",
    warning: "border-warning text-warning hover:bg-warning hover:text-white",
    success: "border-success text-success hover:bg-success hover:text-white",
  },
  light: {
    primary: "bg-primary-50 text-primary hover:bg-primary-100",
    secondary: "bg-secondary-50 text-secondary hover:bg-secondary-100",
    info: "bg-info-50 text-info hover:bg-info-100",
    neutral: "bg-neutral-50 text-neutral hover:bg-neutral-100",
    error: "bg-error-50 text-error hover:bg-error-100",
    warning: "bg-warning-50 text-warning hover:bg-warning-100",
    success: "bg-success-50 text-success hover:bg-success-100",
  },
  flat: {
    secondary: "bg-secondary-50 text-secondary hover:bg-secondary-100 hover:border-transparent",
    info: "bg-info-50 text-info hover:bg-info-100 hover:border-transparent",
    neutral: "bg-neutral-50 text-neutral hover:bg-neutral-100 hover:border-transparent",
    error: "bg-error-50 text-error hover:bg-error-100 hover:border-transparent",
    warning: "bg-warning-50 text-warning hover:bg-warning-100 hover:border-transparent",
    success: "bg-success-50 text-success hover:bg-success-100 hover:border-transparent",
  },
  ghost: {
    primary: "border-primary text-primary hover:bg-primary hover:text-white",
    secondary: "border-secondary text-secondary hover:bg-secondary hover:text-white",
    info: "border-info text-info hover:bg-info hover:text-white",
    neutral: "border-neutral text-neutral hover:bg-neutral hover:text-white",
    error: "border-error text-error hover:bg-error hover:text-white",
    warning: "border-warning text-warning hover:bg-warning hover:text-white",
    success: "border-success text-success hover:bg-success hover:text-white",
  },
  text: {
    primary: "text-primary hover:text-primary-900",
    secondary: "text-secondary hover:text-secondary-900",
    info: "text-info hover:text-info-900",
    neutral: "text-neutral hover:text-neutral-900",
    error: "text-error hover:text-error-900",
    warning: "text-warning hover:text-warning-900",
    success: "text-success hover:text-success-900",
  },
}; 